export const galeria = [
  { titulo: "Producto", src: "/images/gallery/1.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/2.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/3.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/4.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/5.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/6.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/7.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/8.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/9.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/10.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/11.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/12.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/13.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/14.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/15.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/16.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/17.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/18.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/19.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/20.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/21.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/22.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/23.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/24.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/25.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/26.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/27.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/28.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/29.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/30.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/31.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/32.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/33.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/34.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/35.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/36.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/37.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/38.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/39.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/40.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/41.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/42.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/43.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/44.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/45.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/46.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/47.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/48.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/49.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/50.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/51.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/52.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/53.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/54.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/55.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/56.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/57.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/58.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/59.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/60.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/61.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/62.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/63.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/64.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/65.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/66.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/67.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/68.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/69.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/70.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/71.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/72.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/73.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/74.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/75.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/76.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/77.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/78.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/79.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/80.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/81.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/82.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/83.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/84.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/85.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/86.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/87.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/88.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/89.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/90.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/91.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/92.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/93.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/94.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/95.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/96.jpg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/97.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/98.jpeg", precio: 9990, alt: "" },
  { titulo: "Producto", src: "/images/gallery/99.jpeg", precio: 9990, alt: "" },
  {
    titulo: "Producto",
    src: "/images/gallery/100.jpeg",
    precio: 9990,
    alt: "",
  },
  {
    titulo: "Producto",
    src: "/images/gallery/101.jpeg",
    precio: 9990,
    alt: "",
  },
  {
    titulo: "Producto",
    src: "/images/gallery/102.jpeg",
    precio: 9990,
    alt: "",
  },
];
