export const galeria = [
  {
    titulo: "Nutrisse 57 ambar",
    src: "/images/gallery/1.jpeg",
    precio: 5390,
    alt: "",
  },
  {
    titulo: "Ladysoft toallas higienicas",
    src: "/images/gallery/2.jpeg",
    precio: 1790,
    alt: "",
  },
  {
    titulo: "Excellence 6660",
    src: "/images/gallery/3.jpg",
    precio: 6490,
    alt: "",
  },
  {
    titulo: "Kotex toallas higienicas",
    src: "/images/gallery/4.jpeg",
    precio: 2590,
    alt: "",
  },
  {
    titulo: "Nosotras toallas higienicas",
    src: "/images/gallery/5.jpg",
    precio: 2490,
    alt: "",
  },
  {
    titulo: "Para ti toallas higienicas",
    src: "/images/gallery/6.jpeg",
    precio: 1390,
    alt: "",
  },
  {
    titulo: "Para ti toallas higienicas",
    src: "/images/gallery/7.jpeg",
    precio: 990,
    alt: "",
  },
  {
    titulo: "Ladysoft toallas  higienicas",
    src: "/images/gallery/8.jpeg",
    precio: 990,
    alt: "",
  },
  {
    titulo: "Ladysoft toallas higienicas",
    src: "/images/gallery/9.jpeg",
    precio: 990,
    alt: "",
  },
  {
    titulo: "Nosotras toallas higienicas ",
    src: "/images/gallery/10.jpg",
    precio: 990,
    alt: "",
  },
  {
    titulo: "Sedal shampoo",
    src: "/images/gallery/11.jpeg",
    precio: 1990,
    alt: "",
  },
  {
    titulo: "Head & Shoulders shampoo",
    src: "/images/gallery/12.jpeg",
    precio: 3490,
    alt: "",
  },
  {
    titulo: "Sedal shampoo ceramidas",
    src: "/images/gallery/13.jpeg",
    precio: 1990,
    alt: "",
  },
  {
    titulo: "Always toallas higienicas",
    src: "/images/gallery/14.jpeg",
    precio: 3100,
    alt: "",
  },
  {
    titulo: "Nosotras toallas higienicas",
    src: "/images/gallery/15.jpeg",
    precio: 1290,
    alt: "",
  },
  {
    titulo: "Elvive shampoo oleo",
    src: "/images/gallery/16.jpeg",
    precio: 3390,
    alt: "",
  },
  {
    titulo: "Dove shampoo fuerza vital ",
    src: "/images/gallery/17.jpeg",
    precio: 2990,
    alt: "",
  },
  {
    titulo: "Familand shampoo granada",
    src: "/images/gallery/18.jpeg",
    precio: 1990,
    alt: "",
  },
  {
    titulo: "Eucerin shampoo dermo capilar",
    src: "/images/gallery/19.jpeg",
    precio: 11190,
    alt: "",
  },
  {
    titulo: "Eucerin protect sum kids f30",
    src: "/images/gallery/20.jpeg",
    precio: 14990,
    alt: "",
  },
  {
    titulo: "Eucerin crema de mano ph5",
    src: "/images/gallery/21.jpeg",
    precio: 8990,
    alt: "",
  },
  {
    titulo: "Lubriderm crema extra humectante",
    src: "/images/gallery/22.jpeg",
    precio: 6590,
    alt: "",
  },
  {
    titulo: "Nivea crema milk nutritiva 250ml",
    src: "/images/gallery/23.jpeg",
    precio: 3490,
    alt: "",
  },
  {
    titulo: "Pielarmina crema mano",
    src: "/images/gallery/24.jpeg",
    precio: 1390,
    alt: "",
  },
  {
    titulo: "Pielarmina crema hidratante",
    src: "/images/gallery/25.jpeg",
    precio: 3100,
    alt: "",
  },
  {
    titulo: "Eucerin baby crema corporal",
    src: "/images/gallery/26.jpeg",
    precio: 15590,
    alt: "",
  },
  {
    titulo: "Aquafresh cepillo little teeth",
    src: "/images/gallery/27.jpeg",
    precio: 2190,
    alt: "",
  },
  {
    titulo: "Aquafresh cepillo flex 2x1",
    src: "/images/gallery/28.jpeg",
    precio: 1490,
    alt: "",
  },
  {
    titulo: "Dento cepillo duro plus 2x1",
    src: "/images/gallery/29.jpeg",
    precio: 2690,
    alt: "",
  },
  {
    titulo: "Ammen pack colonia",
    src: "/images/gallery/30.jpeg",
    precio: 4290,
    alt: "",
  },
  {
    titulo: "Babyland colonia",
    src: "/images/gallery/31.jpeg",
    precio: 2100,
    alt: "",
  },
  {
    titulo: "Maybelline mascara pestañas",
    src: "/images/gallery/32.jpeg",
    precio: 7690,
    alt: "",
  },
  {
    titulo: "Millefiori cera depilatoria",
    src: "/images/gallery/33.jpeg",
    precio: 4890,
    alt: "",
  },
  {
    titulo: "Millefiori cera depilatoria",
    src: "/images/gallery/34.jpeg",
    precio: 4890,
    alt: "",
  },
  {
    titulo: "Millefiori cera perlas",
    src: "/images/gallery/35.jpeg",
    precio: 2100,
    alt: "",
  },
  {
    titulo: "Huggis toallitas humedas",
    src: "/images/gallery/36.jpeg",
    precio: 2300,
    alt: "",
  },
  {
    titulo: "Pampers toallitas humedas",
    src: "/images/gallery/37.jpeg",
    precio: 1490,
    alt: "",
  },
  {
    titulo: "Proactive toallitas humedas ",
    src: "/images/gallery/38.jpeg",
    precio: 2490,
    alt: "",
  },
  {
    titulo: "Tutte toallitas humedas",
    src: "/images/gallery/39.jpeg",
    precio: 2190,
    alt: "",
  },
  {
    titulo: "Win toallitas humedas",
    src: "/images/gallery/40.jpeg",
    precio: 2190,
    alt: "",
  },
  {
    titulo: "Axe desodorante spray men",
    src: "/images/gallery/41.jpeg",
    precio: 2190,
    alt: "",
  },
  {
    titulo: "Bi-o desodorante spray",
    src: "/images/gallery/42.jpg",
    precio: 2290,
    alt: "",
  },
  {
    titulo: "Dove desodorante spray",
    src: "/images/gallery/43.jpeg",
    precio: 2490,
    alt: "",
  },
  {
    titulo: "Etiquet desodorante crema",
    src: "/images/gallery/44.jpg",
    precio: 1490,
    alt: "",
  },
  {
    titulo: "Etiquet desodorante roll-on men",
    src: "/images/gallery/45.jpeg",
    precio: 1990,
    alt: "",
  },
  {
    titulo: "Lady speed stick desodorante barra",
    src: "/images/gallery/46.jpeg",
    precio: 2490,
    alt: "",
  },
  {
    titulo: "Speed stick desodorante spray men",
    src: "/images/gallery/47.jpeg",
    precio: 2490,
    alt: "",
  },
  {
    titulo: "Nivea desodorante  spray ",
    src: "/images/gallery/48.jpg",
    precio: 2790,
    alt: "",
  },
  {
    titulo: "Nivea desodorante spray",
    src: "/images/gallery/49.jpg",
    precio: 2790,
    alt: "",
  },
  {
    titulo: "Nivea desodorante barra",
    src: "/images/gallery/50.jpg",
    precio: 2790,
    alt: "",
  },
  {
    titulo: "Nivea desodorante roll-on",
    src: "/images/gallery/51.jpg",
    precio: 2790,
    alt: "",
  },
  {
    titulo: "Rexona desodorante men",
    src: "/images/gallery/52.jpeg",
    precio: 2590,
    alt: "",
  },
  {
    titulo: "Rexona desodorante spray",
    src: "/images/gallery/53.jpg",
    precio: 2590,
    alt: "",
  },
  {
    titulo: "Rexona desodorante barra",
    src: "/images/gallery/54.jpg",
    precio: 2590,
    alt: "",
  },
  {
    titulo: "Rexona desodorante barra ",
    src: "/images/gallery/55.jpeg",
    precio: 5090,
    alt: "",
  },
  {
    titulo: "Rexona desodorante barra",
    src: "/images/gallery/56.jpeg",
    precio: 5090,
    alt: "",
  },
  {
    titulo: "Nivea crema de afeitar ",
    src: "/images/gallery/57.jpeg",
    precio: 3490,
    alt: "",
  },
  {
    titulo: "Nivea espuma de afeitar",
    src: "/images/gallery/58.jpeg",
    precio: 4890,
    alt: "",
  },
  {
    titulo: "Listerine enjuague bucal",
    src: "/images/gallery/59.jpg",
    precio: 2090,
    alt: "",
  },
  {
    titulo: "Listerine enjuague bucal",
    src: "/images/gallery/60.jpeg",
    precio: 9390,
    alt: "",
  },
  {
    titulo: "Listerine enjuague bucal",
    src: "/images/gallery/61.jpeg",
    precio: 6190,
    alt: "",
  },
  {
    titulo: "Duo fijador mousse",
    src: "/images/gallery/62.jpg",
    precio: 2290,
    alt: "",
  },
  {
    titulo: "Duo fijador fuerte",
    src: "/images/gallery/63.jpeg",
    precio: 1990,
    alt: "",
  },
  {
    titulo: "Duo fijador fuerte",
    src: "/images/gallery/64.jpg",
    precio: 2790,
    alt: "",
  },
  {
    titulo: "Duo fijador gel ",
    src: "/images/gallery/65.jpeg",
    precio: 2290,
    alt: "",
  },
  {
    titulo: "Fructis gel fijador",
    src: "/images/gallery/66.jpeg",
    precio: 4390,
    alt: "",
  },
  {
    titulo: "VO5 gel fijador",
    src: "/images/gallery/67.jpeg",
    precio: 2990,
    alt: "",
  },
  {
    titulo: "Gillette venus simply",
    src: "/images/gallery/68.jpeg",
    precio: 1590,
    alt: "",
  },
  {
    titulo: "Asepxia jabon azufre",
    src: "/images/gallery/69.jpeg",
    precio: 3490,
    alt: "",
  },
  {
    titulo: "Asepxia jabon forte",
    src: "/images/gallery/70.jpeg",
    precio: 3490,
    alt: "",
  },
  {
    titulo: "Eucerin jabon intimo",
    src: "/images/gallery/72.jpeg",
    precio: 9990,
    alt: "",
  },
  {
    titulo: "le sancy jabon barra",
    src: "/images/gallery/73.jpeg",
    precio: 990,
    alt: "",
  },
  {
    titulo: "Protex jabon barra ",
    src: "/images/gallery/74.jpeg",
    precio: 990,
    alt: "",
  },
  {
    titulo: "Rexona jabon liquido",
    src: "/images/gallery/75.jpeg",
    precio: 2590,
    alt: "",
  },
  {
    titulo: "Simonds jabon liquido",
    src: "/images/gallery/76.jpg",
    precio: 2390,
    alt: "",
  },
  {
    titulo: "Simonds jabon liquido",
    src: "/images/gallery/77.jpg",
    precio: 2390,
    alt: "",
  },
  {
    titulo: "Simonds jabon liquido",
    src: "/images/gallery/78.jpeg",
    precio: 2390,
    alt: "",
  },
  {
    titulo: "Comodity pañal adulto",
    src: "/images/gallery/79.jpeg",
    precio: 3990,
    alt: "",
  },
  {
    titulo: "Plenitud mimi aposito",
    src: "/images/gallery/80.jpeg",
    precio: 3190,
    alt: "",
  },
  {
    titulo: "Sany pañal adulto",
    src: "/images/gallery/81.jpeg",
    precio: 3990,
    alt: "",
  },
  {
    titulo: "Win pañal pants adulto",
    src: "/images/gallery/82.jpeg",
    precio: 5690,
    alt: "",
  },
  {
    titulo: "Win pañal adulto",
    src: "/images/gallery/83.jpeg",
    precio: 11190,
    alt: "",
  },
  {
    titulo: "Win aposito ",
    src: "/images/gallery/84.jpeg",
    precio: 2590,
    alt: "",
  },
  {
    titulo: "Win sabanilla",
    src: "/images/gallery/85.jpeg",
    precio: 3990,
    alt: "",
  },
  {
    titulo: "Babysec pañal",
    src: "/images/gallery/86.jpeg",
    precio: 8100,
    alt: "",
  },
  {
    titulo: "Babysec premiun ",
    src: "/images/gallery/87.jpeg",
    precio: 3990,
    alt: "",
  },
  {
    titulo: "Babysec super premiun",
    src: "/images/gallery/88.jpeg",
    precio: 3690,
    alt: "",
  },
  {
    titulo: "Huggies pañal",
    src: "/images/gallery/89.jpeg",
    precio: 3990,
    alt: "",
  },
  {
    titulo: "Huggies pañal",
    src: "/images/gallery/90.jpeg",
    precio: 4290,
    alt: "",
  },
  {
    titulo: "Pampers premiun",
    src: "/images/gallery/91.jpeg",
    precio: 4690,
    alt: "",
  },
  {
    titulo: "Pampers premiun",
    src: "/images/gallery/92.jpeg",
    precio: 4690,
    alt: "",
  },
  {
    titulo: "Aquafresh pasta dental",
    src: "/images/gallery/93.jpeg",
    precio: 1490,
    alt: "",
  },
  {
    titulo: "Colgate pasta dental",
    src: "/images/gallery/94.jpg",
    precio: 2290,
    alt: "",
  },
  {
    titulo: "Colgate pasta dental",
    src: "/images/gallery/95.jpeg",
    precio: 2290,
    alt: "",
  },
  {
    titulo: "Pepsodent pasta dental",
    src: "/images/gallery/96.jpg",
    precio: 2990,
    alt: "",
  },
  {
    titulo: "Pepsodent pasta dental",
    src: "/images/gallery/97.jpeg",
    precio: 2490,
    alt: "",
  },
  {
    titulo: "Sensodyne pasta dental",
    src: "/images/gallery/98.jpeg",
    precio: 4590,
    alt: "",
  },
  {
    titulo: "Sensodyne pasta dental",
    src: "/images/gallery/99.jpeg",
    precio: 4690,
    alt: "",
  },
  {
    titulo: "Eucerin protect sum",
    src: "/images/gallery/100.jpeg",
    precio: 17290,
    alt: "",
  },
  {
    titulo: "Leblon bloqueador",
    src: "/images/gallery/101.jpeg",
    precio: 1390,
    alt: "",
  },
  {
    titulo: "Simonds pantalla solar",
    src: "/images/gallery/102.jpeg",
    precio: 6190,
    alt: "",
  },
];
