import Head from "next/head";
import Accordeon from "../components/Accordeon";

export default function Branches() {
  return (
    <div>
      <Head>
        <title>Farmacias Belén</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="content">
        <section className="section-1 mt-6">
          <h1 className="text-center">Encuentra tu sucursal más cercana</h1>
          <div>
            <Accordeon />
          </div>
        </section>
      </main>
    </div>
  );
}
