import Head from "next/head";

export default function Branches() {
  return (
    <div>
      <Head>
        <title>Farmacias Belén</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="content"></main>
    </div>
  );
}
