import Head from "next/head";
import Card from "../components/Card";
import { galeria } from "../components/galeria";

export default function Catalogue() {
  return (
    <>
      <div>
        <Head>
          <title>Farmacias Belén</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="content">
          <section className="section-1 mt-6">
            <div className="text-center">
              <h1>Catálogo</h1>
            </div>
            <div>
              <div className="search"></div>
            </div>
            <div className="grid grid-cols-1 items-center justify-center mx-auto w-fit sm:grid-cols-2 gap-3 md:grid-cols-3 lg:grid-cols-4">
              {galeria.map((image, index) => (
                <div key={index} className="mx-auto">
                  <Card
                    src={image.src}
                    titulo={image.titulo}
                    precio={image.precio}
                  />
                </div>
              ))}
            </div>
          </section>
        </main>
      </div>
    </>
  );
}
