import Head from "next/head";
import Form from "../components/Form";

export default function Contact() {
  return (
    <div>
      <Head>
        <title>Farmacias Belén</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="content">
        <section className="section-1 mt-6">
          <Form />
        </section>
      </main>
    </div>
  );
}
