import Head from "next/head";
import Carousel from "../components/Carousel";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Farmacias Belén</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="content">
        <section className="section-1">
          <Hero />
        </section>
        <section className="section-2 mx-auto">
          <div id="destacados">
            <div>
              <h2 className="text-center">Productos destacados</h2>
            </div>
            <div className="flex mx-auto justify-center items-center w-full">
              <Carousel />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
